In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

pd.set_option('display.max_columns', None)    #显示所有列
pd.set_option('display.max_rows', 30)    #显示所有行
pd.set_option('max_colwidth',100)    #设置value的显示长度为100，默认为50

import warnings
warnings.filterwarnings("ignore")

import  seaborn as sns

from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

In [2]:
all_data = pd.read_csv(r'D:\MyData\chenpf8\TianChi_Data\01_Introduction to Financial risk control - Loan default prediction\all_data.csv' ,
                   encoding='UTF-8', index_col=0,header=0)
all_data.head()

loanAmnt  term  interestRate  installment  grade  subGrade  \
id                                                               
0        4.0     5           3.0          3.0      3        21   
1        2.0     5           3.0          2.0      4        16   
2        1.0     5           3.0          1.0      4        17   
3        1.0     3           0.0          1.0      7         3   
4        0.0     3           2.0          0.0      5        11   

    employmentTitle  employmentLength  homeOwnership  annualIncome  \
id                                                                   
0               0.0                 0              2           3.0   
1               3.0                 2              0           1.0   
2               2.0                 3              0           2.0   
3               2.0                 4              1           3.0   
4               0.0                 0              1           0.0   

    verificationStatus  purpose  postCode  regionCode  dti  \
id                                                           
0                    2        0       1.0           3  1.0   
1                    2        0       1.0           2  3.0   
2                    2        0       2.0           1  2.0   
3                    1        1       1.0           1  1.0   
4                    2        3       2.0           2  3.0   

    delinquency_2years  ficoRangeLow  ficoRangeHigh  openAcc  pubRec  \
id                                                                     
0                  0.0           3.0            3.0      0.0     0.0   
1                  0.0           2.0            2.0      2.0     0.0   
2                  0.0           1.0            1.0      1.0     0.0   
3                  0.0           1.0            1.0      1.0     0.0   
4                  0.0           1.0            1.0      2.0     0.0   

    pubRecBankruptcies  revolBal  revolUtil  totalAcc  initialListStatus  \
id                                                                         
0                  0.0       3.0        1.0       0.0                  0   
1                  0.0       2.0        1.0       0.0                  1   
2                  0.0       0.0        1.0       0.0                  0   
3                  0.0       1.0        2.0       0.0                  1   
4                  0.0       0.0        0.0       0.0                  0   

    applicationType  title   n0   n1   n2   n4   n5   n6   n7   n8   n9  n10  \
id                                                                             
0                 0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1                 0    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
2                 0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3                 0    0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
4                 0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

    n11  n12  n13  n14  
id                      
0   0.0  0.0  0.0  0.0  
1   0.0  0.0  0.0  0.0  
2   0.0  0.0  0.0  0.0  
3   0.0  0.0  0.0  0.0  
4   0.0  0.0  0.0  0.0

In [3]:
ntrain = 800000
ntest = 200000
ntrainA = pd.read_csv(r'D:\MyData\chenpf8\TianChi_Data\01_Introduction to Financial risk control - Loan default prediction\trainA_data.csv' ,
                   encoding='UTF-8', index_col=0,header=0)
ntrainA.head()

isDefault
id           
0           1
1           0
2           0
3           0
4           0

In [4]:
train_data = all_data[:ntrain]
train_data = pd.concat((train_data,ntrainA),axis=1)
train_data.head()

loanAmnt  term  interestRate  installment  grade  subGrade  \
id                                                               
0        4.0     5           3.0          3.0      3        21   
1        2.0     5           3.0          2.0      4        16   
2        1.0     5           3.0          1.0      4        17   
3        1.0     3           0.0          1.0      7         3   
4        0.0     3           2.0          0.0      5        11   

    employmentTitle  employmentLength  homeOwnership  annualIncome  \
id                                                                   
0               0.0                 0              2           3.0   
1               3.0                 2              0           1.0   
2               2.0                 3              0           2.0   
3               2.0                 4              1           3.0   
4               0.0                 0              1           0.0   

    verificationStatus  purpose  postCode  regionCode  dti  \
id                                                           
0                    2        0       1.0           3  1.0   
1                    2        0       1.0           2  3.0   
2                    2        0       2.0           1  2.0   
3                    1        1       1.0           1  1.0   
4                    2        3       2.0           2  3.0   

    delinquency_2years  ficoRangeLow  ficoRangeHigh  openAcc  pubRec  \
id                                                                     
0                  0.0           3.0            3.0      0.0     0.0   
1                  0.0           2.0            2.0      2.0     0.0   
2                  0.0           1.0            1.0      1.0     0.0   
3                  0.0           1.0            1.0      1.0     0.0   
4                  0.0           1.0            1.0      2.0     0.0   

    pubRecBankruptcies  revolBal  revolUtil  totalAcc  initialListStatus  \
id                                                                         
0                  0.0       3.0        1.0       0.0                  0   
1                  0.0       2.0        1.0       0.0                  1   
2                  0.0       0.0        1.0       0.0                  0   
3                  0.0       1.0        2.0       0.0                  1   
4                  0.0       0.0        0.0       0.0                  0   

    applicationType  title   n0   n1   n2   n4   n5   n6   n7   n8   n9  n10  \
id                                                                             
0                 0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1                 0    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
2                 0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3                 0    0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
4                 0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

    n11  n12  n13  n14  isDefault  
id                                 
0   0.0  0.0  0.0  0.0          1  
1   0.0  0.0  0.0  0.0          0  
2   0.0  0.0  0.0  0.0          0  
3   0.0  0.0  0.0  0.0          0  
4   0.0  0.0  0.0  0.0          0

In [5]:
test_data = all_data[ntrain:]
test_data.shape

(200000, 41)

In [6]:
X_train = train_data.drop("isDefault", axis=1)
Y_train = train_data["isDefault"]
X_test  = test_data.copy()
X_train.shape, Y_train.shape, X_test.shape

((800000, 41), (800000,), (200000, 41))

In [12]:
# machine learning
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier


from sklearn.linear_model import ElasticNet, Lasso,  BayesianRidge, LassoLarsIC
from sklearn.ensemble import RandomForestRegressor,  GradientBoostingRegressor, GradientBoostingClassifier
from sklearn.kernel_ridge import KernelRidge
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xgb
import lightgbm as lgb

from sklearn.model_selection import KFold
from sklearn.metrics import auc, roc_curve

In [22]:
xgbr = xgb.XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, 
                             learning_rate=0.05, max_depth=3, 
                             min_child_weight=1.7817, n_estimators=2200,
                             reg_alpha=0.4640, reg_lambda=0.8571,
                             subsample=0.5213, silent=1,
                             random_state =7, nthread = -1)

In [10]:
lgbr = lgb.LGBMRegressor(objective='regression',num_leaves=5,
                              learning_rate=0.05, n_estimators=720,
                              max_bin = 55, bagging_fraction = 0.8,
                              bagging_freq = 5, feature_fraction = 0.2319,
                              feature_fraction_seed=9, bagging_seed=9,
                              min_data_in_leaf =6, min_sum_hessian_in_leaf = 11)

In [ ]:
xgb.fit(X_train, Y_train)
Y_pred = xgb.predict(X_test)
xgb.score(X_train, Y_train)
acc_xgb = round(xgb.score(X_train, Y_train) * 100, 2)
acc_xgb

In [24]:
kf = KFold(n_splits=10, shuffle=True, random_state=100)
devscore = []
for tidx, didx in kf.split(X_train.index):
    tf = X_train.iloc[tidx]
    df = X_train.iloc[didx]
    tt = Y_train.iloc[tidx]
    dt = Y_train.iloc[didx]
    xgbr.fit(tf, tt)
    pre = xgbr.predict(df)
    fpr, tpr, thresholds = roc_curve(dt, pre)
    score = auc(fpr, tpr)
    devscore.append(score)
print(np.mean(devscore))

[14:45:23] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480: 
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[14:56:00] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480: 
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[15:06:56] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480: 
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings bu

In [13]:
kf = KFold(n_splits=10, shuffle=True, random_state=100)
devscore = []
for tidx, didx in kf.split(X_train.index):
    tf = X_train.iloc[tidx]
    df = X_train.iloc[didx]
    tt = Y_train.iloc[tidx]
    dt = Y_train.iloc[didx]
    lgbr.fit(tf, tt)
    pre = lgbr.predict(df)
    fpr, tpr, thresholds = roc_curve(dt, pre)
    score = auc(fpr, tpr)
    devscore.append(score)
print(np.mean(devscore))

0.7147860517229272


###  对比发现  XGB  相对于  LGB  花费更多的时间，效果却差不了多少。

In [14]:
Y_pred = lgbr.predict(X_test)
Y_pred

array([0.06691077, 0.31361763, 0.39341981, ..., 0.28774545, 0.22575493,
       0.03766005])

In [15]:
sum(Y_pred)

39922.96411559308

In [16]:
sub = pd.DataFrame()
sub['id'] = test_data.index
sub['isDefault'] = Y_pred
sub.to_csv('submission_lgbr.csv',index=False)

###  K-Fold练习

In [18]:
X_train.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            799990, 799991, 799992, 799993, 799994, 799995, 799996, 799997,
            799998, 799999],
           dtype='int64', name='id', length=800000)

In [21]:
kf = KFold(n_splits=10, shuffle=True, random_state=100)
for tidx, didx in kf.split(X_train.index):
#     tf = X_train.iloc[tidx]
#     df = X_train.iloc[didx]
    print(tidx,len(tidx))
    print(didx,len(didx))

[     0      1      2 ... 799997 799998 799999] 720000
[    12     13     18 ... 799946 799973 799987] 80000
[     0      1      2 ... 799995 799997 799998] 720000
[    21     25     31 ... 799993 799996 799999] 80000
[     1      2      3 ... 799997 799998 799999] 720000
[     0     11     19 ... 799984 799986 799989] 80000
[     0      1      2 ... 799997 799998 799999] 720000
[     7      9     14 ... 799991 799994 799995] 80000
[     0      1      2 ... 799997 799998 799999] 720000
[     3      6     15 ... 799963 799969 799980] 80000
[     0      1      2 ... 799997 799998 799999] 720000
[     4      8     16 ... 799974 799976 799977] 80000
[     0      1      2 ... 799997 799998 799999] 720000
[    20     33     36 ... 799964 799982 799988] 80000
[     0      1      2 ... 799997 799998 799999] 720000
[    22     23     28 ... 799975 799978 799979] 80000
[     0      2      3 ... 799995 799996 799999] 720000
[     1      5     17 ... 799992 799997 799998] 80000
[     0      1     

In [ ]:
from sklearn.metrics import roc_auc_score
y_true = np.array([0, 0, 1, 1])
y_scores = np.array([0.1, 0.4, 0.35, 0.8])
print('AUC socre:',roc_auc_score(y_true, y_scores))